// automatically generated; please do not modify.

#ifndef H_adas_dds_idl
#define H_adas_dds_idl

#include <builtin/ShmemInfoSupport.h>
#include <adas/routing/RoutingWayPointSupport.h>
#include <adas/examples/HelloWorldSupport.h>
#include <adas/examples/CameraImageSupport.h>
#include <adas/localization/FeaturePointsSupport.h>
#include <adas/localization/CameraVisualSupport.h>
#include <adas/localization/ImuVisualSupport.h>
#include <adas/localization/FeaturePointSupport.h>
#include <adas/perception/BBoxesSupport.h>
#include <adas/perception/CameraImageSupport.h>
#include <adas/perception/ImageSupport.h>
#include <adas/perception/BBoxSupport.h>
#include <adas/common/Vector3fSupport.h>
#include <adas/common/Pose2Support.h>
#include <adas/common/ClockOffsetSupport.h>
#include <adas/common/Pose2ArraySupport.h>
#include <adas/common/Point3Support.h>
#include <adas/common/Point2Support.h>
#include <adas/dw/objectSupport.h>
#include <adas/dw/laneSupport.h>
#include <adas/dw/objectsSupport.h>
#include <adas/obstacle/ObstaclePathPredictionSupport.h>
#include <adas/obstacle/UssObstaclesSupport.h>
#include <adas/obstacle/UssObstacleSupport.h>
#include <adas/obstacle/ScalaObstaclesSupport.h>
#include <adas/obstacle/ObstacleStatesSupport.h>
#include <adas/obstacle/EyeObstaclesSupport.h>
#include <adas/obstacle/RadarObstacleSupport.h>
#include <adas/obstacle/ObstaclePathPredictionsSupport.h>
#include <adas/obstacle/ScalaObstacleSupport.h>
#include <adas/obstacle/ContiRadarObjectsSupport.h>
#include <adas/obstacle/ContiRadarObjectSupport.h>
#include <adas/obstacle/ScalaVehicleStateSupport.h>
#include <adas/obstacle/EyeObstacleSupport.h>
#include <adas/obstacle/ObstacleStateSupport.h>
#include <adas/obstacle/RadarObstaclesSupport.h>
#include <adas/eyeQ4/ObjectEyeQ4Support.h>
#include <adas/eyeQ4/TrafficSignEyeQ4Support.h>
#include <adas/eyeQ4/LanesEyeQ4Support.h>
#include <adas/eyeQ4/ObjectsEyeQ4Support.h>
#include <adas/eyeQ4/NextLaneEyeQ4Support.h>
#include <adas/eyeQ4/LaneEyeQ4Support.h>
#include <adas/eyeQ4/TrafficSignsEyeQ4Support.h>
#include <adas/eyeQ4/EyeQ4Support.h>
#include <adas/pointcloud/PointXYZISupport.h>
#include <adas/pointcloud/PointCloudXYZISupport.h>
#include <adas/pointcloud/PointCloudXYZRTHISupport.h>
#include <adas/pointcloud/PointXYZRTHISupport.h>
#include <adas/pointcloud/PointCloudHeaderSupport.h>
#include <adas/obstacles/PedestriansSupport.h>
#include <adas/obstacles/BikesSupport.h>
#include <adas/obstacles/Obstacles2DSupport.h>
#include <adas/obstacles/BikeSupport.h>
#include <adas/obstacles/CarSupport.h>
#include <adas/obstacles/ObstaclesSupport.h>
#include <adas/obstacles/CornerRadarRawObjectSupport.h>
#include <adas/obstacles/ConeSupport.h>
#include <adas/obstacles/TruckSupport.h>
#include <adas/obstacles/TrucksSupport.h>
#include <adas/obstacles/BusesSupport.h>
#include <adas/obstacles/CornerRadarRawObjectsSupport.h>
#include <adas/obstacles/PedestrianSupport.h>
#include <adas/obstacles/ObstacleSupport.h>
#include <adas/obstacles/Obstacle2DSupport.h>
#include <adas/obstacles/CarsSupport.h>
#include <adas/obstacles/BusSupport.h>
#include <adas/obstacles/ConesSupport.h>
#include <adas/novatel/NovatelInsCovSSupport.h>
#include <adas/novatel/NovatelImuSupport.h>
#include <adas/novatel/NovatelCommonHeaderSupport.h>
#include <adas/novatel/NovatelShortHeaderSupport.h>
#include <adas/novatel/NovatelInsPvaXSupport.h>
#include <adas/novatel/NovatelPositionSupport.h>
#include <adas/novatel/NovatelOdometrySupport.h>
#include <adas/novatel/NovatelBestPosSupport.h>
#include <adas/novatel/NovatelRawImuSXSupport.h>
#include <adas/novatel/NovatelInsPvaSSupport.h>
#include <adas/novatel/NovatelRawImuSSupport.h>
#include <adas/planing/ReferencePlannerStateSupport.h>
#include <adas/lane/SampledLineSupport.h>
#include <adas/lane/LaneSupport.h>
#include <adas/lane/LaneInformationSupport.h>
#include <adas/lane/LineHeaderSupport.h>
#include <adas/lane/RoadmapSupport.h>
#include <adas/lane/LaneBoundaryPoly3Support.h>
#include <adas/lane/LaneIdSupport.h>
#include <adas/lane/SampledLinesSupport.h>
#include <adas/lane/LaneBoundarySupport.h>
#include <adas/lane/RoadSupport.h>
#include <adas/lane/EyeqVehicleLinesSupport.h>
#include <adas/lane/LaneSectionSupport.h>
#include <adas/lane/LaneBoundariesSupport.h>
#include <adas/lane/EyeqVehicleLineSupport.h>
#include <adas/control/ControlCmdSupport.h>
#include <adas/control/TrajectoriesSupport.h>
#include <adas/control/VehicleStateSupport.h>
#include <adas/control/TrajectoryPointSupport.h>
#include <adas/control/TwistSupport.h>
#include <adas/control/ControlMonitorSupport.h>
#include <adas/control/TrajectorySupport.h>
#include <adas/control/TrajectoryCoeffSupport.h>
#include <adas/map/MapLinesSupport.h>
#include <adas/map/TrafficSignsSupport.h>
#include <adas/map/MapLinePointSupport.h>
#include <adas/map/StopSignSupport.h>
#include <adas/map/TrafficSignSupport.h>
#include <adas/map/YieldSignsSupport.h>
#include <adas/map/LightRegionSupport.h>
#include <adas/map/StopSignsSupport.h>
#include <adas/map/YieldSignSupport.h>
#include <adas/map/TrafficLightsSupport.h>
#include <adas/map/MapLineSupport.h>
#include <adas/map/TrafficLightSupport.h>
#include <adas/vlp/VlpScanSupport.h>
#include <adas/vlp/VlpPacketSupport.h>
#include <adas/vlp/VlpGpsPacketSupport.h>
#include <adas/vlp/VlpBlockSupport.h>
#include <ros_ported/sensor/JointStateSupport.h>
#include <ros_ported/sensor/PointFieldSupport.h>
#include <ros_ported/sensor/NavSatStatusSupport.h>
#include <ros_ported/sensor/ImuSupport.h>
#include <ros_ported/sensor/PointCloud2Support.h>
#include <ros_ported/sensor/NavSatFixSupport.h>
#include <ros_ported/sensor/CanMsgFrameSupport.h>
#include <ros_ported/sensor/TimeReferenceSupport.h>
#include <ros_ported/std/UInt32Support.h>
#include <ros_ported/std/Int16Support.h>
#include <ros_ported/std/UInt16Support.h>
#include <ros_ported/std/Float64Support.h>
#include <ros_ported/std/Int64Support.h>
#include <ros_ported/std/UInt8Support.h>
#include <ros_ported/std/StringSupport.h>
#include <ros_ported/std/UInt64Support.h>
#include <ros_ported/std/TimeSupport.h>
#include <ros_ported/std/DurationSupport.h>
#include <ros_ported/std/ColorRGBASupport.h>
#include <ros_ported/std/HeaderSupport.h>
#include <ros_ported/std/BoolSupport.h>
#include <ros_ported/std/Int32Support.h>
#include <ros_ported/std/Float32Support.h>
#include <ros_ported/std/Int8Support.h>
#include <ros_ported/visualization/MarkerSupport.h>
#include <ros_ported/mkz/SteeringCmdSupport.h>
#include <ros_ported/mkz/SurroundReportSupport.h>
#include <ros_ported/mkz/ParkingBrakeSupport.h>
#include <ros_ported/mkz/BrakeCmdSupport.h>
#include <ros_ported/mkz/ThrottleReportSupport.h>
#include <ros_ported/mkz/FuelLevelReportSupport.h>
#include <ros_ported/mkz/BrakeReportSupport.h>
#include <ros_ported/mkz/BrakeInfoReportSupport.h>
#include <ros_ported/mkz/TirePressureReportSupport.h>
#include <ros_ported/mkz/WiperSupport.h>
#include <ros_ported/mkz/AmbientLightSupport.h>
#include <ros_ported/mkz/TwistCmdSupport.h>
#include <ros_ported/mkz/HillStartAssistSupport.h>
#include <ros_ported/mkz/WatchdogCounterSupport.h>
#include <ros_ported/mkz/WheelPositionReportSupport.h>
#include <ros_ported/mkz/GearSupport.h>
#include <ros_ported/mkz/WheelSpeedReportSupport.h>
#include <ros_ported/mkz/TurnSignalSupport.h>
#include <ros_ported/mkz/Misc1ReportSupport.h>
#include <ros_ported/mkz/ThrottleCmdSupport.h>
#include <ros_ported/mkz/ThrottleInfoReportSupport.h>
#include <ros_ported/mkz/TurnSignalCmdSupport.h>
#include <ros_ported/mkz/GearRejectSupport.h>
#include <ros_ported/mkz/SteeringReportSupport.h>
#include <ros_ported/mkz/GearCmdSupport.h>
#include <ros_ported/mkz/GearReportSupport.h>
#include <ros_ported/geometry/PoseWithCovarianceSupport.h>
#include <ros_ported/geometry/TwistStampedSupport.h>
#include <ros_ported/geometry/QuaternionSupport.h>
#include <ros_ported/geometry/PoseStampedSupport.h>
#include <ros_ported/geometry/TwistWithCovarianceSupport.h>
#include <ros_ported/geometry/PointSupport.h>
#include <ros_ported/geometry/OdometrySupport.h>
#include <ros_ported/geometry/PolygonSupport.h>
#include <ros_ported/geometry/TwistSupport.h>
#include <ros_ported/geometry/Vector3Support.h>
#include <ros_ported/geometry/PoseSupport.h>
#include <ros_ported/geometry/PolygonStampedSupport.h>
#include <ros_ported/geometry/Point32Support.h>
#include <ros_ported/geometry/PathSupport.h>

#endif
