set(CMAKE_SYSTEM_NAME QNX)

set(PLATFORM_LIBS m socket)
set(RTIDDS_ARCH armv8QNX7.0.0qcc_gpp5.4.0)
set(VINAIADASDDS_ARCH armv8QNX7.0.0qcc_gpp5.4.0)

#set(CMAKE_CXX_COMPILER $ENV{QNX_HOST}/usr/bin/qcc)
#set(CMAKE_C_COMPILER $ENV{QNX_HOST}/usr/bin/qcc)
set(CMAKE_CROSSCOMPILING TRUE)
add_definitions(
    -DRTI_QNX
)

#set(CMAKE_C_FLAGS "-lang-c -Vgcc/5.4.0,gcc_ntoaarch64le " CACHE INTERNAL "CMAKE_C_FLAGS" FORCE)
#set(CMAKE_CXX_FLAGS "-lang-c++ -Vgcc/5.4.0,gcc_ntoaarch64le -DNDEBUG" CACHE INTERNAL "CMAKE_CXX_FLAGS" FORCE)
#set(CMAKE_C_FLAGS_RELEASE "-DNDEBUG" CACHE INTERNAL "CMAKE_C_FLAGS_RELEASE" FORCE)
#set(CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG" CACHE INTERNAL "CMAKE_CXX_FLAGS_RELEASE" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
